// 1. Definición de tipos para mayor seguridad
export type Role = 'ADMIN' | 'CHEF' | 'ELEVATED' | 'USER';

// 2. Estructura de permisos centralizada (by GPT)
export const ROLE_PERMISSIONS: Record<Exclude<Role, 'ELEVATED'>, string[]> = {
  ADMIN: [
    "DELETE /api/allergens/{id}",
    "DELETE /api/config/notifications/logs",
    "DELETE /api/config/presence/logs",
    "DELETE /api/config/ai-keys/{provider}",
    "DELETE /api/chat/chats/{chatId}",
    "DELETE /api/notifications/group/{groupId}",
    "DELETE /api/notifications/{id}",
    "DELETE /api/order-details/{orderId}/{productId}",
    "DELETE /api/orders/{id}",
    "DELETE /api/orders/{id}/review-lock",
    "DELETE /api/orders/{id}/review-collaboration/fields/lock",
    "DELETE /api/recipe-allergens/recipe/{recipeId}/allergen/{allergenId}",
    "DELETE /api/recipe-allergens/{id}",
    "DELETE /api/recipe-components/{id}",
    "DELETE /api/recipes/{id}",
    "DELETE /api/suppliers/{id}",
    "DELETE /api/users/{id}",
    "DELETE /api/weekly-plans",
    "GET /api/allergens",
    "GET /api/allergens/search",
    "GET /api/allergens/{id}",
    "GET /api/auth/role",
    "GET /api/auth/validate",
    "GET /api/admin/blockchain/blocks",
    "GET /api/admin/blockchain/blocks/{blockNumber}",
    "GET /api/admin/blockchain/mempool",
    "GET /api/admin/blockchain/stats",
    "GET /api/admin/blockchain/verify",
    "GET /api/config/ai-keys",
    "GET /api/chat/chats",
    "GET /api/chat/chats/{chatId}/messages",
    "GET /api/chat/chats/{chatId}/messages/page",
    "GET /api/chat/providers",
    "GET /api/config/advanced",
    "GET /api/config/advanced/audit-log",
    "GET /api/config/alerts",
    "GET /api/config/alerts/audit-log",
    "GET /api/config/audit-log",
    "GET /api/config/current",
    "GET /api/config/incidents",
    "GET /api/config/incidents/audit-log",
    "GET /api/config/notifications",
    "GET /api/config/notifications/audit-log",
    "GET /api/config/predictions",
    "GET /api/config/predictions/audit-log",
    "GET /api/config/presence",
    "GET /api/config/presence/audit-log",
    "GET /api/config/security",
    "GET /api/config/security/audit-log",
    "GET /api/config/sessions",
    "GET /api/config/sessions/audit-log",
    "GET /api/config/units",
    "GET /api/config/units/active",
    "GET /api/incident-types",
    "GET /api/incident-types/all",
    "GET /api/incident-types/{id}",
    "GET /api/incidents",
    "GET /api/incidents/{id}",
    "GET /api/incidents/{id}/attachable-audits",
    "GET /api/incidents/{id}/chat",
    "GET /api/incidents/{id}/chat/attachments/{messageId}",
    "GET /api/incidents/{id}/export/pdf",
    "GET /api/inventory-audits",
    "GET /api/inventory-audits/by-date-range",
    "GET /api/inventory-audits/type/{type}",
    "GET /api/inventory-audits/{id}",
    "GET /api/kitchen-reports",
    "GET /api/kitchen-reports/export/pdf",
    "GET /api/mcp/alerts/active",
    "GET /api/mcp/analysis/cost-breakdown",
    "GET /api/mcp/analysis/menu-optimizer",
    "GET /api/mcp/analysis/reorder-suggestions",
    "GET /api/mcp/analysis/stock-health-score",
    "GET /api/mcp/analysis/waste-risk",
    "GET /api/mcp/context",
    "GET /api/mcp/crises/active",
    "GET /api/mcp/expiring-soon",
    "GET /api/mcp/orders/pending",
    "GET /api/mcp/products",
    "GET /api/mcp/products/{id}/batches",
    "GET /api/mcp/products/{id}/consumption-history",
    "GET /api/mcp/products/{id}/deep",
    "GET /api/mcp/products/{id}/forecast",
    "GET /api/mcp/products/{id}/ledger",
    "GET /api/mcp/recipes/by-allergen-exclusion",
    "GET /api/mcp/recipes/{id}/deep",
    "GET /api/mcp/recipes/{id}/feasibility",
    "GET /api/mcp/search",
    "GET /api/mcp/suppliers/{id}/deep",
    "GET /api/mcp/weekly-plan/current/deep",
    "GET /api/notifications",
    "GET /api/notifications/unread-count",
    "GET /api/order-audits",
    "GET /api/order-audits/by-date-range",
    "GET /api/order-audits/by-order/{id}",
    "GET /api/order-audits/by-user/{id}",
    "GET /api/order-audits/{id}",
    "GET /api/order-details",
    "GET /api/order-details/order/{orderId}",
    "GET /api/order-details/product/{productId}",
    "GET /api/order-details/{orderId}/{productId}",
    "GET /api/orders",
    "GET /api/orders/daterange",
    "GET /api/orders/reception/pending",
    "GET /api/orders/search",
    "GET /api/orders/status/{status}",
    "GET /api/orders/total-cost",
    "GET /api/orders/user/{userId}",
    "GET /api/orders/{id}/review-lock",
    "GET /api/orders/{id}/review-collaboration",
    "GET /api/orders/{id}",
    "GET /api/orders/{id}/missing-items",
    "GET /api/orders/{id}/pdf",
    "GET /api/products",
    "GET /api/products/export/excel",
    "GET /api/products/codebar/{codebar}",
    "GET /api/products/search",
    "GET /api/products/{id}",
    "GET /api/products/with-ledger",
    "GET /api/products/hidden",
    "GET /api/products/ledger-integrity",
    "GET /api/products/{id}/ledger/pdf",
    "GET /api/products/batches",
    "GET /api/products/batches/by-code/{batchCode}",
    "GET /api/products/batches/expired",
    "GET /api/products/batches/expiring",
    "GET /api/products/batches/product/{productId}",
    "GET /api/products/batches/typeahead",
    "GET /api/recipe-allergens",
    "GET /api/recipe-allergens/allergen/{allergenId}",
    "GET /api/recipe-allergens/recipe/{recipeId}",
    "GET /api/recipe-allergens/recipe/{recipeId}/allergens",
    "GET /api/recipe-audits",
    "GET /api/recipe-audits/by-date-range",
    "GET /api/recipe-audits/by-recipe/{id}",
    "GET /api/recipe-audits/by-user/{id}",
    "GET /api/recipe-audits/{id}",
    "GET /api/recipe-components",
    "GET /api/recipe-components/recipe/{recipeId}",
    "GET /api/recipe-components/{id}",
    "GET /api/recipe-cooking-audit",
    "GET /api/recipe-cooking-audit/date-range",
    "GET /api/recipe-cooking-audit/recipe/{recipeId}",
    "GET /api/recipe-cooking-audit/search",
    "GET /api/recipe-cooking-audit/user/{userId}",
    "GET /api/recipe-drafts",
    "GET /api/recipe-drafts/{id}",
    "GET /api/recipes",
    "GET /api/recipes/cookable",
    "GET /api/recipes/maxcost",
    "GET /api/recipes/search",
    "GET /api/recipes/hidden",
    "GET /api/recipes/{id}",
    "GET /api/recipes/{id}/pdf",
    "GET /api/stats/products",
    "GET /api/stats/recipes",
    "GET /api/stats/recipes/average-cost",
    "GET /api/stats/recipes/with-allergens/count",
    "GET /api/stats/recipes/without-allergens/count",
    "GET /api/stats/users",
    "GET /api/stock-alerts",
    "GET /api/stock-alerts/forecast",
    "GET /api/stock-alerts/forecast/{productId}",
    "GET /api/stock-alerts/history",
    "GET /api/stock-alerts/history/{productId}",
    "GET /api/stock-alerts/predictions",
    "GET /api/stock-alerts/{productId}",
    "GET /api/stock-ledger/consumption/{productId}",
    "GET /api/stock-ledger/history/{productId}",
    "GET /api/stock-ledger/snapshot/{productId}",
    "GET /api/stock-ledger/verify-all",
    "GET /api/stock-ledger/verify/{productId}",
    "GET /api/suppliers",
    "GET /api/suppliers/search",
    "GET /api/suppliers/{id}",
    "GET /api/traceability/batch/{batchId}/cookings",
    "GET /api/traceability/crisis",
    "GET /api/traceability/crisis/history",
    "GET /api/traceability/crisis/{crisisId}",
    "GET /api/traceability/crisis/{crisisId}/report/download",
    "GET /api/traceability/forward",
    "GET /api/traceability/reverse/{cookingAuditId}",
    "GET /api/user-activity",
    "GET /api/user-activity/user/{userId}",
    "GET /api/users",
    "GET /api/users/by-role/{role}",
    "GET /api/users/hidden",
    "GET /api/users/search",
    "GET /api/users/students",
    "GET /api/users/students/unassigned",
    "GET /api/users/teachers",
    "GET /api/users/teachers/search",
    "GET /api/weekly-plans",
    "GET /api/weekly-plans/current",
    "GET /api/weekly-plans/metrics/students",
    "GET /api/weekly-plans/{planId}",
    "GET /api/weekly-plans/{planId}/pdf",
    "GET /api/weekly-plans/{planId}/stock-requirements",
    "PATCH /api/config/units/{id}/toggle",
    "PATCH /api/incident-types/{id}/toggle-active",
    "PATCH /api/incidents/{id}/close",
    "PATCH /api/incidents/{id}/open",
    "PATCH /api/notifications/read-all",
    "PATCH /api/notifications/{id}/read",
    "PATCH /api/chat/chats/{chatId}",
    "PATCH /api/chat/chats/{chatId}/provider",
    "PATCH /api/orders/{id}/status",
    "PATCH /api/products/{id}/toggle-hidden",
    "PATCH /api/recipe-drafts/{id}/approve",
    "PATCH /api/recipe-drafts/{id}/reject",
    "PATCH /api/recipes/{id}/toggle-hidden",
    "PATCH /api/users/batch/teacher",
    "PATCH /api/users/batch/transfer-teacher",
    "PATCH /api/users/teachers/{fromTeacherId}/transfer-all/{toTeacherId}",
    "PATCH /api/users/teachers/{teacherId}/students/hidden",
    "PATCH /api/users/{id}/hidden",
    "PATCH /api/weekly-plans/{planId}/activate",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/confirm",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/restore",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/students/{studentId}/cancel",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/students/{studentId}/restore",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/unconfirm",
    "PATCH /api/weekly-plans/{planId}/deactivate",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/cancel",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/confirm",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/restore",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/students/{studentId}/cancel",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/students/{studentId}/restore",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/unconfirm",
    "POST /api/allergens",
    "POST /api/admin/blockchain/rebuild-all",
    "POST /api/admin/blockchain/sync-stock",
    "POST /api/chat/chats",
    "POST /api/config/ai-keys",
    "POST /api/config/units",
    "POST /api/incident-types",
    "POST /api/incidents",
    "POST /api/incidents/{id}/audits",
    "POST /api/incidents/{id}/audits/{attachmentId}/revert",
    "POST /api/incidents/{id}/chat/mark-read",
    "POST /api/incidents/{id}/chat",
    "POST /api/mcp/bulk/orders",
    "POST /api/mcp/bulk/products",
    "POST /api/mcp/bulk/recipes",
    "POST /api/mcp/tools/adjust-stock",
    "POST /api/mcp/tools/confirm-slot/{planId}/{slotId}",
    "POST /api/mcp/tools/cook-recipe",
    "POST /api/mcp/tools/create-order",
    "POST /api/mcp/tools/plan-slot",
    "POST /api/mcp/tools/quarantine-batch",
    "POST /api/mcp/tools/report-incident",
    "POST /api/notifications/role/{role}",
    "POST /api/notifications/send",
    "POST /api/notifications/user/{username}",
    "POST /api/order-details",
    "POST /api/orders",
    "POST /api/orders/reception",
    "POST /api/orders/{id}/review-lock",
    "POST /api/orders/{id}/review-lock/heartbeat",
    "POST /api/orders/{id}/review-collaboration/request",
    "POST /api/orders/{id}/review-collaboration/admit/{userId}",
    "POST /api/orders/{id}/review-collaboration/fields/lock",
    "POST /api/orders/{id}/review-collaboration/fields/patch",
    "POST /api/orders/search-by-products",
    "POST /api/products/batches/{batchId}/withdraw",
    "POST /api/recipe-allergens",
    "POST /api/recipe-allergens/{recipeId}/{allergenId}",
    "POST /api/recipe-components/recipe/{recipeId}",
    "POST /api/recipes",
    "POST /api/recipes/cook",
    "POST /api/recipes/cook/{auditId}/revert",
    "POST /api/recipes/requirements",
    "POST /api/stock-alerts/batch",
    "POST /api/stock-ledger/batch",
    "POST /api/stock-ledger/manual-adjustment",
    "POST /api/suppliers",
    "POST /api/traceability/crisis/activate",
    "POST /api/traceability/crisis/lift",
    "POST /api/users",
    "POST /api/users/{id}/de-escalate",
    "POST /api/users/{id}/escalate",
    "POST /api/weekly-plans",
    "PUT /api/allergens/{id}",
    "PUT /api/config/ai-keys",
    "PUT /api/config/advanced",
    "PUT /api/config/alerts",
    "PUT /api/config/incidents",
    "PUT /api/config/notifications",
    "PUT /api/config/predictions",
    "PUT /api/config/presence",
    "PUT /api/config/security",
    "PUT /api/config/sessions",
    "PUT /api/config/units/{id}",
    "PUT /api/incident-types/{id}",
    "PUT /api/order-details/{orderId}/{productId}",
    "PUT /api/orders/{id}",
    "PUT /api/products/{id}",
    "PUT /api/products/{id}/stock-manual",
    "PUT /api/recipe-components/{id}",
    "PUT /api/recipes/{id}",
    "PUT /api/suppliers/{id}",
    "PUT /api/users/{id}",
    "PUT /api/weekly-plans/{planId}"
  ],
  CHEF: [
    "DELETE /api/chat/chats/{chatId}",
    "DELETE /api/notifications/{id}",
    "DELETE /api/orders/{id}/review-lock",
    "DELETE /api/orders/{id}/review-collaboration/fields/lock",
    "DELETE /api/recipe-allergens/recipe/{recipeId}/allergen/{allergenId}",
    "GET /api/allergens",
    "GET /api/allergens/search",
    "GET /api/allergens/{id}",
    "GET /api/auth/role",
    "GET /api/auth/validate",
    "GET /api/chat/chats",
    "GET /api/chat/chats/{chatId}/messages",
    "GET /api/chat/chats/{chatId}/messages/page",
    "GET /api/chat/providers",
    "GET /api/incident-types",
    "GET /api/incident-types/all",
    "GET /api/incidents",
    "GET /api/incidents/{id}",
    "GET /api/incidents/{id}/attachable-audits",
    "GET /api/incidents/{id}/chat",
    "GET /api/incidents/{id}/chat/attachments/{messageId}",
    "GET /api/mcp/alerts/active",
    "GET /api/mcp/analysis/cost-breakdown",
    "GET /api/mcp/analysis/menu-optimizer",
    "GET /api/mcp/analysis/reorder-suggestions",
    "GET /api/mcp/analysis/stock-health-score",
    "GET /api/mcp/analysis/waste-risk",
    "GET /api/mcp/context",
    "GET /api/mcp/crises/active",
    "GET /api/mcp/expiring-soon",
    "GET /api/mcp/orders/pending",
    "GET /api/mcp/products",
    "GET /api/mcp/products/{id}/batches",
    "GET /api/mcp/products/{id}/consumption-history",
    "GET /api/mcp/products/{id}/deep",
    "GET /api/mcp/products/{id}/forecast",
    "GET /api/mcp/products/{id}/ledger",
    "GET /api/mcp/recipes/by-allergen-exclusion",
    "GET /api/mcp/recipes/{id}/deep",
    "GET /api/mcp/recipes/{id}/feasibility",
    "GET /api/mcp/search",
    "GET /api/mcp/suppliers/{id}/deep",
    "GET /api/mcp/weekly-plan/current/deep",
    "GET /api/notifications",
    "GET /api/notifications/unread-count",
    "GET /api/order-details",
    "GET /api/order-details/order/{orderId}",
    "GET /api/order-details/product/{productId}",
    "GET /api/order-details/{orderId}/{productId}",
    "GET /api/orders",
    "GET /api/orders/daterange",
    "GET /api/orders/reception/pending",
    "GET /api/orders/search",
    "GET /api/orders/status/{status}",
    "GET /api/orders/total-cost",
    "GET /api/orders/user/{userId}",
    "GET /api/orders/{id}/review-lock",
    "GET /api/orders/{id}/review-collaboration",
    "GET /api/orders/{id}",
    "GET /api/orders/{id}/missing-items",
    "GET /api/orders/{id}/pdf",
    "GET /api/products",
    "GET /api/products/export/excel",
    "GET /api/products/codebar/{codebar}",
    "GET /api/products/search",
    "GET /api/products/{id}",
    "GET /api/products/with-ledger",
    "GET /api/products/ledger-integrity",
    "GET /api/products/{id}/ledger/pdf",
    "GET /api/products/batches",
    "GET /api/products/batches/by-code/{batchCode}",
    "GET /api/products/batches/expired",
    "GET /api/products/batches/expiring",
    "GET /api/products/batches/product/{productId}",
    "GET /api/products/batches/typeahead",
    "GET /api/recipe-allergens",
    "GET /api/recipe-allergens/allergen/{allergenId}",
    "GET /api/recipe-allergens/recipe/{recipeId}",
    "GET /api/recipe-allergens/recipe/{recipeId}/allergens",
    "GET /api/recipe-components",
    "GET /api/recipe-components/recipe/{recipeId}",
    "GET /api/recipe-components/{id}",
    "GET /api/recipe-drafts",
    "GET /api/recipe-drafts/{id}",
    "GET /api/recipes",
    "GET /api/recipes/cookable",
    "GET /api/recipes/maxcost",
    "GET /api/recipes/search",
    "GET /api/recipes/{id}",
    "GET /api/recipes/{id}/pdf",
    "GET /api/stock-alerts",
    "GET /api/stock-alerts/forecast",
    "GET /api/stock-alerts/forecast/{productId}",
    "GET /api/stock-alerts/history",
    "GET /api/stock-alerts/history/{productId}",
    "GET /api/stock-alerts/predictions",
    "GET /api/stock-alerts/{productId}",
    "GET /api/suppliers",
    "GET /api/suppliers/search",
    "GET /api/suppliers/{id}",
    "GET /api/traceability/batch/{batchId}/cookings",
    "GET /api/traceability/crisis",
    "GET /api/traceability/crisis/history",
    "GET /api/traceability/crisis/{crisisId}",
    "GET /api/traceability/forward",
    "GET /api/traceability/reverse/{cookingAuditId}",
    "GET /api/user-activity/my-students",
    "GET /api/user-activity/user/{userId}",
    "GET /api/users/students",
    "GET /api/users/teachers",
    "GET /api/users/teachers/search",
    "GET /api/weekly-plans",
    "GET /api/weekly-plans/current",
    "GET /api/weekly-plans/metrics/students",
    "GET /api/weekly-plans/{planId}",
    "GET /api/weekly-plans/{planId}/pdf",
    "GET /api/weekly-plans/{planId}/stock-requirements",
    "PATCH /api/incidents/{id}/open",
    "PATCH /api/notifications/read-all",
    "PATCH /api/notifications/{id}/read",
    "PATCH /api/orders/{id}/status",
    "PATCH /api/products/{id}/toggle-hidden",
    "PATCH /api/recipes/{id}/toggle-hidden",
    "PATCH /api/weekly-plans/{planId}/activate",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/confirm",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/unconfirm",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/restore",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/students/{studentId}/cancel",
    "PATCH /api/weekly-plans/{planId}/days/{dayOfWeek}/students/{studentId}/restore",
    "PATCH /api/weekly-plans/{planId}/deactivate",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/cancel",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/confirm",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/restore",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/students/{studentId}/cancel",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/students/{studentId}/restore",
    "PATCH /api/weekly-plans/{planId}/slots/{slotId}/unconfirm",
    "PATCH /api/chat/chats/{chatId}",
    "PATCH /api/chat/chats/{chatId}/provider",
    "POST /api/allergens",
    "POST /api/chat/chats",
    "POST /api/config/units",
    "POST /api/incident-types",
    "POST /api/incidents",
    "POST /api/incidents/{id}/audits",
    "POST /api/incidents/{id}/chat/mark-read",
    "POST /api/incidents/{id}/chat",
    "POST /api/mcp/bulk/orders",
    "POST /api/mcp/bulk/products",
    "POST /api/mcp/bulk/recipes",
    "POST /api/mcp/tools/confirm-slot/{planId}/{slotId}",
    "POST /api/mcp/tools/cook-recipe",
    "POST /api/mcp/tools/create-order",
    "POST /api/mcp/tools/plan-slot",
    "POST /api/mcp/tools/report-incident",
    "POST /api/order-details",
    "POST /api/orders",
    "POST /api/orders/reception",
    "POST /api/orders/{id}/review-lock",
    "POST /api/orders/{id}/review-lock/heartbeat",
    "POST /api/orders/{id}/review-collaboration/request",
    "POST /api/orders/{id}/review-collaboration/admit/{userId}",
    "POST /api/orders/{id}/review-collaboration/fields/lock",
    "POST /api/orders/{id}/review-collaboration/fields/patch",
    "POST /api/orders/search-by-products",
    "POST /api/products/batches/{batchId}/withdraw",
    "POST /api/recipe-allergens",
    "POST /api/recipe-allergens/{recipeId}/{allergenId}",
    "POST /api/recipe-components/recipe/{recipeId}",
    "POST /api/recipes",
    "POST /api/recipes/cook",
    "POST /api/recipes/cook/{auditId}/revert",
    "POST /api/recipes/requirements",
    "POST /api/stock-alerts/batch",
    "POST /api/users/{id}/de-escalate",
    "POST /api/users/{id}/escalate",
    "POST /api/weekly-plans",
    "PUT /api/allergens/{id}",
    "PUT /api/order-details/{orderId}/{productId}",
    "PUT /api/orders/{id}",
    "PUT /api/products/{id}",
    "PUT /api/products/{id}/stock-manual",
    "PUT /api/recipe-components/{id}",
    "PUT /api/recipes/{id}",
    "PUT /api/weekly-plans/{planId}"
  ],
  USER: [
    "DELETE /api/chat/chats/{chatId}",
    "DELETE /api/notifications/{id}",
    "DELETE /api/recipe-drafts/{id}",
    "GET /api/allergens",
    "GET /api/allergens/search",
    "GET /api/allergens/{id}",
    "GET /api/auth/role",
    "GET /api/auth/validate",
    "GET /api/chat/chats",
    "GET /api/chat/chats/{chatId}/messages",
    "GET /api/chat/chats/{chatId}/messages/page",
    "GET /api/chat/providers",
    "GET /api/mcp/alerts/active",
    "GET /api/mcp/analysis/cost-breakdown",
    "GET /api/mcp/analysis/menu-optimizer",
    "GET /api/mcp/analysis/reorder-suggestions",
    "GET /api/mcp/analysis/stock-health-score",
    "GET /api/mcp/analysis/waste-risk",
    "GET /api/mcp/context",
    "GET /api/mcp/crises/active",
    "GET /api/mcp/expiring-soon",
    "GET /api/mcp/orders/pending",
    "GET /api/mcp/products",
    "GET /api/mcp/products/{id}/batches",
    "GET /api/mcp/products/{id}/consumption-history",
    "GET /api/mcp/products/{id}/deep",
    "GET /api/mcp/products/{id}/forecast",
    "GET /api/mcp/products/{id}/ledger",
    "GET /api/mcp/recipes/by-allergen-exclusion",
    "GET /api/mcp/recipes/{id}/deep",
    "GET /api/mcp/recipes/{id}/feasibility",
    "GET /api/mcp/search",
    "GET /api/mcp/suppliers/{id}/deep",
    "GET /api/mcp/weekly-plan/current/deep",
    "GET /api/notifications",
    "GET /api/notifications/unread-count",
    "GET /api/orders/{id}",
    "GET /api/orders/{id}/pdf",
    "GET /api/products",
    "GET /api/products/export/excel",
    "GET /api/products/codebar/{codebar}",
    "GET /api/products/search",
    "GET /api/products/{id}",
    "GET /api/products/with-ledger",
    "GET /api/products/batches",
    "GET /api/products/batches/by-code/{batchCode}",
    "GET /api/products/batches/expired",
    "GET /api/products/batches/expiring",
    "GET /api/products/batches/product/{productId}",
    "GET /api/products/batches/typeahead",
    "GET /api/recipe-allergens",
    "GET /api/recipe-allergens/allergen/{allergenId}",
    "GET /api/recipe-allergens/recipe/{recipeId}",
    "GET /api/recipe-allergens/recipe/{recipeId}/allergens",
    "GET /api/recipe-components",
    "GET /api/recipe-components/recipe/{recipeId}",
    "GET /api/recipe-components/{id}",
    "GET /api/recipe-drafts/mine",
    "GET /api/recipe-drafts/{id}",
    "GET /api/recipes",
    "GET /api/recipes/maxcost",
    "GET /api/recipes/search",
    "GET /api/recipes/{id}",
    "GET /api/recipes/{id}/pdf",
    "GET /api/users/teachers",
    "GET /api/users/teachers/search",
    "PATCH /api/notifications/read-all",
    "PATCH /api/notifications/{id}/read",
    "PATCH /api/chat/chats/{chatId}",
    "PATCH /api/chat/chats/{chatId}/provider",
    "POST /api/config/units",
    "POST /api/chat/chats",
    "POST /api/mcp/bulk/orders",
    "POST /api/mcp/bulk/products",
    "POST /api/mcp/bulk/recipes",
    "POST /api/orders",
    "POST /api/recipe-drafts",
    "PUT /api/recipe-drafts/{id}"
  ]
};

// 3. Estructura de Árbol (Trie) para evaluación O(1) real de permisos
type TrieNode = {
  methods: Set<string>;
  children: Map<string, TrieNode>;
  wildcard?: TrieNode; // Para segmentos dinámicos como {id}, {codebar}, etc.
};

class PermissionTrie {
  root: TrieNode = { methods: new Set(), children: new Map() };

  add(permission: string) {
    const [method, path] = permission.split(' ');
    const segments = path.split('/').filter(Boolean);
    let current = this.root;

    for (const segment of segments) {
      // Si contiene {}, lo tratamos como un parámetro dinámico (wildcard)
      if (segment.startsWith('{') && segment.endsWith('}')) {
        if (!current.wildcard) {
          current.wildcard = { methods: new Set(), children: new Map() };
        }
        current = current.wildcard;
      } else {
        if (!current.children.has(segment)) {
          current.children.set(segment, { methods: new Set(), children: new Map() });
        }
        current = current.children.get(segment)!;
      }
    }
    current.methods.add(method);
  }

  // Complejidad O(K) donde K es la cantidad de fragmentos (/api/products/123 -> K=3)
  // Prácticamente equivalente a O(1) independiente del número total de permisos.
  check(method: string, path: string): boolean {
    const segments = path.split('/').filter(Boolean);

    // Búsqueda en el árbol
    const search = (node: TrieNode, index: number): boolean => {
      // Si hemos procesado todos los segmentos, verificamos que el método HTTP coincida
      if (index === segments.length) {
        return node.methods.has(method);
      }

      const segment = segments[index];

      // 1. Prioridad: Coincidencia de ruta exacta estática (ej: 'api', 'products')
      if (node.children.has(segment) && search(node.children.get(segment)!, index + 1)) {
        return true;
      }

      // 2. Fallback: Coincidencia con comodín (dinámicos como {id}, {status})
      if (node.wildcard && search(node.wildcard, index + 1)) {
        return true;
      }

      return false;
    };

    return search(this.root, 0);
  }
}

// 4. Precomputamos los árboles para cada rol en la inicialización (Solo se ejecuta 1 vez)
const roleTries = new Map<Role, PermissionTrie>();

export function initPermissions() {
  for (const [role, permissions] of Object.entries(ROLE_PERMISSIONS) as [Exclude<Role, 'ELEVATED'>, string[]][]) {
    const trie = new PermissionTrie();
    for (const p of permissions) {
      trie.add(p);
    }
    roleTries.set(role, trie);
  }
}

// Inicializamos los árboles
initPermissions();

// 5. Funciones de utilidad para el interceptor
export function hasPermission(userRole: Role, method: string, url: string): boolean {
  const normalizedRole = userRole === 'ELEVATED' ? 'CHEF' : userRole;
  const trie = roleTries.get(normalizedRole as Role);
  if (!trie) return false;

  return trie.check(method, url);
}

export function getUrlPattern(url: string): string {
  return url.split('?')[0];
}